### PR TITLE
add $(DESTDIR) in make install function and some fixes

### PR DESCRIPTION
**Pull request by sl1pkn07**
changes
- add $(DESTDIR) to some makfiles (only in install function) in some ports (the rest have these variable). ideal for package maintainers
- some fixes:
    - libtiff, romfs, aalib, sdlmixer : fix missing rule to creation some folders needed for install sources/headers/binaries
    - libjpeg, sdl, sdlmixer, ode: some headers have executable bit (755). change all to 644
    - libmikmod: fix capitalization. makefile in linux don't recognize the $ECHO function (fail build). change to lowercase $echo.
    - aalib: remove older CSV folders
    - sdlimage: fix libfpeg.a not found (before search libjpg.a and get error, but the builds continue)

TODO: some ports need create subdirectories under build time. some port include these subdirs, others need create by hand.
need found the best (and pretty, because my method is too ugly, like https://github.com/ps2dev/ps2sdk-ports/issues/2#issuecomment-48207999 ) solution for this,  (i not senior coder, only little fixes)
i think the best method is change that ports to other structure, like ports without these behavior (like libtiff, for example)

the packages with this issue: libid3tag, libmad, libmikmod, madplay, ode, romfs, sdlgfx and sdlttf, 

greetings

### CODE REVIEW

**Comment by sp193** [comment]
I just realized that $DESTDIR wouldn't work as you think, after hitting the "merge" button. It is currently compiling fine because $DESTDIR isn't set... but once it is, the path will become something like
/path/to/destdir/usr/local/ps2dev/ps2sdk ($DESTDIR, followed by $PS2SDK).
I'll roll-back the $DESTDIR stuff, while keeping the other changes. If you want to come up with a better system, please submit a new pull request.

**Comment by sl1pkn07** [comment]
https://www.gnu.org/prep/standards/html_node/DESTDIR.html

**Comment by sp193** [comment]
That's the thing; $(bindir) is likely a relative path. Our $PS2SDK environmental variable contains a full path to the ps2sdk directory, which is typically /usr/local/ps2dev/ps2sdk.
If you want to use DESTDIR here, you must either make it so that the use of $PS2SDK and $DESTDIR are mutually exclusive, or make them somehow play nice with each other.

**Comment by sl1pkn07** [comment]
Nope if use for creating package distribution (linux) instead build by hand

**Comment by sl1pkn07** [comment]
Because need first (handled internally) install in a "fakeroot" directory. This is posible if DESTDIR is set before prefix install path

**Comment by sp193** [comment]
Okay, that makes more sense. How about the double DESTDIR prefixes that the expat install rule has?

**Comment by sp193** [comment]
I'm assuming that it's not meant to be there. I've fixed that and reinstated your changes.

**Pull request merged**
