### PR TITLE
Update dependecies compiled from original source

### PR DESCRIPTION
**Pull request by fjtrujy**
## Description
This PR is about the update of these libraries that they are a git submodule.
Now is being compiled using ./configure and the needed flags.

- Zlib to latest version (using configure)
- libpng to latest version (using configure)
- libtap to the latest version (using configure)

Additionally, all the git submodules have been removed, and now the makefile does the git clone internally.

Thanks

### CODE REVIEW

**Comment by rickgaiser** [comment]
Great! But I don't see any changes to freetype2? Also keep in mind that recently some effort has been made to make freetype2 smaller: https://github.com/ps2dev/ps2sdk-ports/pull/45. Are the same modules selected as before?

**Comment by fjtrujy** [comment]
Hello @rickgaiser,
Yes, in the end, I didn't change anything in freetype2 because already it was using the latest version.

So I suppose that everything should be as it was.

I'm going to remove it from the description.

Thanks

**Comment by rickgaiser** [comment]
I'm getting the following error when doing 'make all':
```
ar: /home/rgaiser/dev/ps2dev/ps2dev/ps2sdk/ports/lib/libz.a: Bestand of map bestaat niet
Makefile:46: recipe for target 'lib/libSDL_image.a' failed
make[1]: *** [lib/libSDL_image.a] Error 9
make[1]: Map '/home/rgaiser/dev/ps2dev/ps2sdk-ports/sdlimage' wordt verlaten
Makefile:117: recipe for target 'sdlimage' failed
make: *** [sdlimage] Error 2
```
I think it's becouse libz.a is installed in $(PS2SDK)/ee instead of $(PS2SDK)/ports. @fjtrujy can you take a look?

**Comment by fjtrujy** [comment]
Yes, you're right!
The compilation of `zlib` just requires the output folder, so even less ps2 specific code.
Creating PR

**Pull request merged**
