### PR TITLE
unzip

### PR DESCRIPTION
**Pull request by KrahJohlito**
@rickgaiser can you take a look at this please, I have no idea if this is "complete".. I test compiled and it builds and installs and I can link to it in OPL but idk if this is the right way to go about it..

http://www.winimage.com/zLibDll/minizip.html this is the source of the complete lib, it seemed unnecessary to include zip and encryption/decryption so I've only included the unzip portion to keep the lib smaller.. no idea how to go about crediting the author so I just kept the changelog? etc etc

thanks for your time

### CODE REVIEW

**Comment by rickgaiser** [comment]
It looks like an improved version of minizip/unzip is included as part of zlib, that is already part of ps2sdk-ports:
https://github.com/madler/zlib/tree/master/contrib/minizip

Is it possible to remove all source files from this PR, and only have the Makefile compile the sources from zlib?

**Comment by rickgaiser** [comment]
I think it's ready for merge. Convert from draft to normal PR and merge?

**Comment by KrahJohlito** [comment]
Sure thanks, I just wanted to test it first and it works all good.. haven't done much with makefiles before

**Comment by rickgaiser** [comment]
Thanks, the Makefile looks good. Merging.

**Pull request merged**
