### PR TITLE
Added LibYAML

### PR DESCRIPTION
**Pull request by Based-Skid**
Added Libyaml for Working with the YAML Data Serialization Language.

YAML is a superset of JSON. This means We can also work with JSON data with LibYAML.

### CODE REVIEW

**Comment by fjtrujy** [comment]
Have you made any change in the YML library or it is directly the source code being compiled as it is?

Thanks

**Comment by Based-Skid** [comment]
No changes to libyaml.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by fjtrujy** [comment]
Then is not needed to include the source code, just add it as a git submodule

**Comment by fjtrujy** [comment]
This PR is no longer needed because the library is included here: https://github.com/ps2dev/ps2sdk-ports/pull/61

I didn't modify anything about the LIBYAML original source code, this is how it needs to be.

Thanks

**Comment by fjtrujy** [comment]
Closing PR because was included in #61 
Thanks

**Pull request closed without merging**
