### PR TITLE
 Update SDL 1.2 

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Comment by fjtrujy** [comment]
I think this is not the way to follow.... in the past was done like this, but this is not a good idea anymore.
My suggestion is to create a fork of `SDL` in `ps2dev` and then you make a PR with your changes to a separate branch called `ee-v1.2.XX` on the same way we did for `lua`: `https://github.com/ps2dev/lua/tree/ee-v5.4.6`

Anyway, do you think that this still makes sense, have you tried to use instead this: `https://github.com/libsdl-org/sdl12-compat`? in theory this makes the current SDL 2.0 implementation compatible with 1.2, without any kind of extra implementation.

**Comment by Wolf3s** [comment]
Else i would close it and add sdl-conpat instead.

**Comment by fjtrujy** [comment]
> Second idea to replace sdl 1.2 to sdl_compat1.2, it's pretty simple just remove the entire sdl ports and add it, But considering that we would preserve SDL1.2 as legacy i need to access to fork SDL1.2 repository.

I won't say that we actually want to keep the current SDL1.2 implementation as it is full of bugs and no one guarantees that current status is working as expected.
The less and more "mainstream" we are, the better, so skip supporting SDL1.2 and do it through sdl_compat1.2 I think is the best idea...

I have never tried it, please try it and let us know

**Comment by Wolf3s** [comment]
> > Second idea to replace sdl 1.2 to sdl_compat1.2, it's pretty simple just remove the entire sdl ports and add it, But considering that we would preserve SDL1.2 as legacy i need to access to fork SDL1.2 repository.
> 
> I won't say that we actually want to keep the current SDL1.2 implementation as it is full of bugs and no one guarantees that current status is working as expected. The less and more "mainstream" we are, the better, so skip supporting SDL1.2 and do it through sdl_compat1.2 I think is the best idea...
> 
> I have never tried it, please try it and let us know

Now you got it, I will close once i solved the ps2gl pull request since the idea should discard it the SDL1.2.

**Comment by Wolf3s** [comment]
@fjtrujy https://github.com/Wolf3s/PS2SDL-1.2.15/tree/ee-ps2-1.2.15

**Pull request closed without merging**
